# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Prepare python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      # Install Required Package
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run Scraper
        run: |
          python src/main.py --key ${{ secrets.LLMKEY }}

      - name: Push to origin master
        run: |
          echo start push
          git config --global user.name "aidan"
          git config --global user.email "nathaniel2014@163.com"
          
          git add -A
          git commit -m $(date '+%Y-%m-%d')
          git push
        
      

      
